#!/usr/bin/env bash

set -ex

export HOME_DIR=$PWD

mkdir -p $HOME_DIR/$GO_SRC_DIR
cp -r git-cloudfoundry-grace/* $HOME_DIR/$GO_SRC_DIR

pushd $GO_SRC_DIR
  GOPATH=$HOME_DIR go build .
  tar -czf grace.tar.gz grace
  mv grace.tar.gz $HOME_DIR/grace-tarball

  # build grace for the busybox docker image
  GOPATH=$HOME_DIR go build -tags 'busybox' .
  mv grace $HOME_DIR/grace-docker
  cp Dockerfile $HOME_DIR/grace-docker
popd

gracesha1sum=$(sha1sum $HOME_DIR/grace-tarball/grace.tar.gz | cut -d' ' -f1)

cat <<HERE > $HOME_DIR/grace-config/grace-config.json
{ "grace_tarball_checksum": "${gracesha1sum}" }
HERE
